version: '3.8'

services:
  kafka1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      # Define both internal and external listeners
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      # Advertise both internal and external addresses
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - kafka-network

  kafdrop1:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      # Use the internal listener for container-to-container communication
      KAFKA_BROKERCONNECT: kafka1:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka1
    networks:
      - kafka-network

  kafka2:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 2@kafka2:9095
      # Define both internal and external listeners
      KAFKA_CFG_LISTENERS: INTERNAL://:29094,EXTERNAL://:9094,CONTROLLER://:9095
      # Advertise both internal and external addresses
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka2:29094,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - kafka-network

  kafdrop2:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9001:9000"
    environment:
      # Use the internal listener for container-to-container communication
      KAFKA_BROKERCONNECT: kafka2:29094
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka2
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge